-- =====================================================================
-- Regras iniciais de categorização (padrões em MAIÚSCULAS, sem acento).
-- São expressões regulares (JavaScript). Prioridade menor vence.
-- Correções feitas no app viram regras "aprendidas" (prioridade 1).
-- =====================================================================

insert into regras_categoria (alvo, tipo, padrao, categoria_id, prioridade, origem)
select r.alvo, 'regex', r.padrao, c.id, r.prioridade, 'sistema'
from (values
  -- ------------------------- ITENS DE NOTA ---------------------------
  ('item', '\b(CERV|CERVEJA|CHOPP?|VINHO|ESPUMANTE|VODKA|WHISKY?|GIN|CACHACA|RUM|TEQUILA|LICOR|SKOL|BRAHMA|HEINEKEN|BUDWEISER|STELLA ARTOIS|AMSTEL|SPATEN|ITAIPAVA|CORONA|PATAGONIA|EISENBAHN|ANTARCTICA|BAVARIA)\b', 'Bebidas alcoólicas', 30),
  ('item', '\b(CONGELAD[OA]S?|LASANHA|PIZZA CONG)\b', 'Mercado', 32),
  ('item', '(AGUA SANITARIA|ALVEJANTE|\bDETERG|\bSABAO\b|SABAO (EM )?(PO|LIQ|BARRA)|AMACIANTE|DESINFET|LIMPADOR|MULTIUSO|DESENGORD|ESPONJA|PANO (DE )?(CHAO|PRATO|MULTIUSO|LIMPEZA)|SACO (P/ |PARA |DE )?LIXO|SACOS? LIXO|LUSTRA ?MOVEIS|\bOMO\b|\bYPE\b|BOMBRIL|PALHA DE ACO|INSETICIDA|TIRA ?MANCHAS?|VANISH|SAPOLIO|\bCLORO\b|LIMPA ?(VIDROS?|PISOS?|FORNO)|\bVEJA\b|LAVA ?(ROUPAS?|LOUCAS?)|ALCOOL (46|70|GEL|LIQ))', 'Limpeza', 35),
  ('item', '(SABONETE|SHAMP|CONDICIONADOR|CREME DENT|\bCR DENT|PASTA DENT|ESCOVA DENT|FIO DENTAL|ENXAGUANTE|DESODOR|\bDESOD\b|ANTITRANSP|PAPEL HIG|PAP HIG|\bP HIG|ABSORVENTE|FRALDA|LENCO UMED|LENCOS UMED|COTONETE|HASTES FLEX|BARBEAR|GILLETTE|PRESTOBARBA|HIDRATANTE|PROTETOR SOLAR|MAQUIAGEM|ESMALTE|ACETONA|TINTURA|COLONIA|PERFUME|\bBATOM\b|DEMAQUIL|CREME (P/|PARA )?(PELE|CORPO|MAOS|PENTEAR))', 'Higiene e beleza', 40),
  ('item', '(\d+ ?MG\b|\bCPR\b|COMPRIMIDO|CAPSULA|\bCAPS\b|XAROPE|POMADA|\bGOTAS\b|DIPIRONA|PARACETAMOL|IBUPROFENO|DORFLEX|NEOSALDINA|BUSCOPAN|OMEPRAZOL|LOSARTANA|AMOXICILINA|VITAMINA|SORO FISIO|CURATIVO|BAND.?AID|\bGAZE\b|ESPARADRAPO|TERMOMETRO|PRESERVATIVO|TESTE (DE )?GRAVIDEZ|REPELENTE|ANTISSEPTICO|COLIRIO|LOCAO)', 'Farmácia e saúde', 45),
  ('item', '(RACAO|PEDIGREE|WHISKAS|FRISKIES|GOLDEN FORMULA|PREMIER PET|AREIA (P/ |PARA |HIGIENICA )?GATOS?|AREIA SANIT|PETISCO (P/ )?(CAES|CAO|GATO)|SACHE (P/ )?(CAES|CAO|GATO)|\bCAES\b|\bGATOS\b|ANTIPULGAS|COLEIRA)', 'Pet', 45),
  ('item', '(\bMOLHO|EXTRATO DE TOMATE|\bEXTRATO\b|CATCHUP|KETCHUP|MISTURA (P/|PARA)? ?BOLO|\bMASSA\b|MACARRAO|TEMPERO)', 'Mercado', 47),
  ('item', '(BATATA DOCE|BATATA INGLESA|BATATA LAVADA|BATATA KG)', 'Hortifruti', 48),
  ('item', '(REFRIG|\bREFRI\b|COCA.?COLA|\bCOCA\b|GUARANA|PEPSI|FANTA|SPRITE|\bSUCO\b|NECTAR|AGUA MIN|AGUA (C/|S/|COM |SEM )GAS|\bAGUA\b|ENERGETICO|CHA GELADO|ICE TEA|ISOTONICO|GATORADE|POWERADE|H2OH|KOMBUCHA|TONICA|\bSCHWEPPES\b|DEL VALLE|TODDYNHO)', 'Bebidas', 50),
  ('item', '(CHOCOLATE|\bCHOC\b|BOMBOM|\bBALAS?\b|PIRULITO|CHICLETE|GOMA DE MASCAR|BISCOITO|\bBISC\b|BOLACHA|WAFER|SALGADINHO|\bCHIPS\b|BATATA (PALHA|FRITA|CHIPS|ONDULADA)|PIPOCA|SORVETE|PICOLE|\bDOCE\b|PACOCA|BRIGADEIRO|NUTELLA|BARRA (DE )?CEREAL|CEREAL BARRA|RUFFLES|DORITOS|CHEETOS|FANDANGOS|TRAKINAS|OREO|KIT ?KAT|LACTA|GAROTO|AMENDOIM|TORCIDA|ELMA CHIPS|\bMARSHMALLOW|\bGELATINA\b|\bPUDIM\b|SUSPIRO)', 'Doces e snacks', 55),
  ('item', '(\bPAO\b|\bPAES\b|\bCUCA\b|\bBOLO\b|\bSONHO\b|CROISSANT|BISNAGUINHA|TORRADA|\bROSCA\b|SALGADO ASSADO|\bPASTEL\b|COXINHA|ESFIHA|EMPADA|\bBAGUETE|CIABATTA|SNACK PADARIA)', 'Padaria', 58),
  ('item', '(\bCARNE|BOVIN|ALCATRA|PICANHA|MAMINHA|FRALDINHA|COSTELA|PATINHO|\bACEM\b|COXAO|\bMOIDA\b|\bFILE\b|FRANGO|\bPEITO\b|\bCOXA\b|SOBRECOXA|\bASA\b|\bASAS\b|LINGUICA|SALSICHA|\bBACON\b|PRESUNTO|MORTADELA|SALAME|\bPERU\b|QUEIJO|MUSSARELA|MUCARELA|MOZZARELLA|\bSUINO|PERNIL|\bLOMBO\b|BISTECA|PEIXE|TILAPIA|SALMAO|CAMARAO|MERLUZA|HAMBURGUER|NUGGETS?|\bCHESTER\b|\bKG\b.*(BOV|SUI|FGO))', 'Carnes e frios', 60),
  ('item', '(\bBANANA|\bMACAS?\b|LARANJA|\bLIMAO|\bMAMAO|MELANCIA|\bMELAO|\bUVAS?\b|ABACAXI|\bMANGA\b|\bPERAS?\b|MORANGO|\bKIWI|ABACATE|TOMATE|\bCEBOLA|\bALHO\b|\bBATATA|CENOURA|\bALFACE|RUCULA|REPOLHO|BROCOLIS|\bCOUVE|PEPINO|PIMENTAO|ABOBRINHA|ABOBORA|MORANGA|BETERRABA|CHUCHU|BERINJELA|MANDIOCA|\bAIPIM|AGRIAO|ESPINAFRE|CHEIRO VERDE|\bSALSA\b|CEBOLINHA|GENGIBRE|\bHORTI|\bFLV\b|BERGAMOTA|TANGERINA|\bVAGEM|QUIABO|COGUMELO|CHAMPIGNON)', 'Hortifruti', 70),
  ('item', '(CAMISETA|CAMISA|\bCALCA\b|BERMUDA|\bMEIAS?\b|CUECA|CALCINHA|\bSUTIA|\bTENIS\b|SAPATO|CHINELO|HAVAIANAS|\bBLUSA|JAQUETA|VESTIDO|\bSHORT)', 'Vestuário', 75),
  ('item', '(PILHA|LAMPADA|\bFITA\b|\bVELAS?\b|FOSFORO|ISQUEIRO|PAPEL ALUMINIO|PAPEL FILME|PAPEL MANTEIGA|GUARDANAPO|PAPEL TOALHA|COPO DESC|COPOS DESC|PRATO DESC|TALHER|FILTRO (DE )?CAFE|FILTRO PAPEL|VASSOURA|\bRODO\b|\bBALDE\b|PREGADOR|CABIDE|EXTENSAO|\bTOMADA|CARVAO|ACENDEDOR|POTE PLAST|\bPOTE\b|ORGANIZADOR|SACOLA)', 'Casa e utilidades', 75),
  ('item', '(GASOLINA|ETANOL|DIESEL|\bGNV\b|ALCOOL COMUM|ALCOOL HIDRAT|ARLA)', 'Combustível', 20),
  ('item', '(CABO USB|CARREGADOR|\bFONE\b|\bMOUSE\b|TECLADO|PEN ?DRIVE|CARTAO (DE )?MEMORIA|\bHDMI\b)', 'Eletrônicos', 75),
  ('item', '(\bBUFFET|A LA MINUTA|ALA MINUTA|REFEICAO|MARMITA|\bXIS\b|\bX-|HAMBURG(ER|UER) ARTES|\bPIZZA\b|\bLANCHE\b|\bESPETO\b|RODIZIO|PRATO FEITO|\bPF\b|\bCOUVERT|TAXA DE SERVICO|GORJETA|\bCHOPE\b|\bPORCAO\b|\bSUSHI|TEMAKI|\bCAFE EXPRESSO|CAPPUCCINO|\bESPRESSO\b)', 'Restaurante e delivery', 78),
  ('item', '(\bARROZ|FEIJAO|MACARRAO|\bMASSA\b|FARINHA|ACUCAR|\bSAL\b|\bOLEO\b|AZEITE|\bCAFE\b|\bLEITE|IOGURTE|MANTEIGA|MARGARINA|REQUEIJAO|CREME DE LEITE|\bOVOS?\b|MOLHO|EXTRATO|CATCHUP|KETCHUP|MAIONESE|MOSTARDA|TEMPERO|\bCALDO\b|VINAGRE|FERMENTO|\bAVEIA|GRANOLA|CEREAL|ACHOCOLATADO|NESCAU|\bTODDY\b|\bMILHO|ERVILHA|SARDINHA|\bATUM\b|AZEITONA|PALMITO|ERVA.?MATE|CHIMARRAO|GELEIA|\bMEL\b|POLVILHO|\bAMIDO|MAISENA|LENTILHA|GRAO DE BICO|QUINOA|CHIA|LINHACA|\bCHA\b|ADOCANTE|CONDIMENTO|PIMENTA|OREGANO|COLORAU|\bTRIGO\b|MISTURA P/? BOLO|\bSOPA\b|MIOJO|LAMEN|NISSIN|PATE\b|SALSICHA LATA)', 'Mercado', 80),

  -- -------------------- LANÇAMENTOS (descrição) ----------------------
  ('transacao', '(FATURA|PAGTO? ?(DE )?CART|PAGAMENTO (DE )?CARTAO|NU PAGAMENTOS|ITAUCARD|PAGAMENTO RECEBIDO|PAGAMENTO EFETUADO|PAG FAT|DEB AUT FAT|CARTAO NUBANK)', 'Pagamento de fatura', 10),
  ('transacao', '(APLICACAO|\bAPLIC\b|RESGATE|\bRDB\b|\bCDB\b|\bLCI\b|\bLCA\b|TESOURO|POUPANCA|CAIXINHA|DINHEIRO GUARDADO|GUARDADO|INVESTIMENTO|APL AUT|RES AUT|RENDE FACIL|\bCDI\b)', 'Investimentos', 15),
  ('transacao', '(MERCADO ?LIVRE|MERCADOPAGO|MERCADO PAGO|\bMP \*|SHOPEE|AMAZON(?! PRIME)|ALIEXPRESS|SHEIN)', 'Outros', 18),
  ('transacao', '(\bIOF\b|TARIFA|ANUIDADE|JUROS|ENCARGOS|\bMULTA\b|CESTA (DE )?SERV|PACOTE (DE )?SERV|SEGURO CARTAO)', 'Tarifas e juros', 20),
  ('transacao', '(\bIPVA\b|\bIPTU\b|\bDARF\b|RECEITA FED|\bDAS\b|\bGRU\b|LICENCIAMENTO|DETRAN)', 'Impostos', 22),
  ('transacao', '(\bUBER\b|UBER ?TRIP|\b99 ?(APP|POP|TAXI|RIDE)|99APP|CABIFY|ESTACIONAMENTO|ESTAPAR|PARE BEM|PEDAGIO|SEM PARAR|CONECTCAR|VELOE|\bTAXI\b|ONIBUS|RODOVIARIA|\bTRI\b|TRENSURB|METRO)', 'Transporte', 30),
  ('transacao', '(\bPOSTO\b|AUTO POSTO|\bSHELL\b|IPIRANGA|PETROBRAS|\bBR MANIA|BUFFON|SIM REDE|COMBUSTIV|\bRAIZEN)', 'Combustível', 30),
  ('transacao', '(IFOOD|\bIFD\b|IFD\*|RAPPI|ZE DELIVERY|AIQFOME|RESTAUR|LANCHERIA|LANCHES|\bLANCHE|PIZZ|BURGER|MC ?DONALDS|SUBWAY|OUTBACK|CHURRASC|\bBAR\b|BOTECO|CAFETERIA|STARBUCKS|SPOLETO|MADERO|GALETERIA|SUSHI|TEMAKI|BISTRO|CHOPERIA|CERVEJARIA|SORVETERIA|HAMBURG|FOOD)', 'Restaurante e delivery', 35),
  ('transacao', '(PADARIA|PANIFIC|CONFEITARIA|DOCERIA)', 'Padaria', 36),
  ('transacao', '(ACOUGUE|CASA DE CARNES|FRIGORIFICO|CASA DAS CARNES)', 'Carnes e frios', 36),
  ('transacao', '(FRUTEIRA|HORTIFRUTI|SACOLAO|VERDURAS|FEIRA)', 'Hortifruti', 37),
  ('transacao', '(SUPERMERC|SUPER MERC|\bMERCADO\b|MERCEARIA|MINIMERCADO|ATACAD|ATACAREJO|ZAFFARI|BOURBON|\bASSAI\b|CARREFOUR|\bNACIONAL\b|\bBIG\b|WALMART|UNIDASUL|UNIDA SUL|GUANABARA|ANGELONI|COMPER|PAO DE ACUCAR|\bEXTRA\b|\bSTOK\b|MAXXI|FORT ATACADISTA|\bMAKRO\b|DALLONDER|ASUN)', 'Mercado', 38),
  ('transacao', '(FARMAC|DROGA|PANVEL|\bRAIA\b|DROGASIL|SAO JOAO|PAGUE MENOS|ULTRAFARMA|LABORAT|CLINICA|HOSPITAL|UNIMED|ODONTO|DENTIST|MEDIC|EXAME|ORTOPED|FISIOTER|PSICOLOG|OTICA)', 'Farmácia e saúde', 40),
  ('transacao', '(\bCEEE\b|\bRGE\b|\bCPFL|EQUATORIAL|\bENEL\b|CEMIG|\bLIGHT\b|\bCOPEL\b|CELESC|CORSAN|AEGEA|\bDMAE\b|SABESP|SANEP|\bVIVO\b|\bCLARO\b|\bTIM\b|\bOI\b|NET SERV|\bSKY\b|INTERNET|CONDOMINIO|ALUGUEL|ULTRAGAZ|LIQUIGAS|SUPERGASBRAS|COPAGAZ|\bGAS\b|ENERGIA|SANEAMENTO)', 'Contas da casa', 40),
  ('transacao', '(NETFLIX|SPOTIFY|AMAZON PRIME|PRIME VIDEO|DISNEY|\bHBO\b|\bMAX\b|GLOBOPLAY|YOUTUBE|APPLE\.COM|APPLE COM|ITUNES|GOOGLE ?(ONE|STORAGE|PLAY|\*)|MICROSOFT|XBOX|PLAYSTATION|DEEZER|PARAMOUNT|CLAUDE\.AI|ANTHROPIC|OPENAI|CHATGPT|ICLOUD|DROPBOX|CRUNCHYROLL|TWITCH)', 'Assinaturas', 42),
  ('transacao', '(PETZ|COBASI|PET ?SHOP|AGROPECUARIA|VETERIN|AGROVET)', 'Pet', 44),
  ('transacao', '(RENNER|RIACHUELO|\bC ?& ?A\b|\bCEA\b|\bZARA\b|HERING|CENTAURO|NETSHOES|DECATHLON|MARISA|YOUCOM|CALCADOS|CALCADOS|MODAS|CONFECC)', 'Vestuário', 46),
  ('transacao', '(KABUM|FAST SHOP|MAGAZINE LUIZA|MAGALU|CASAS BAHIA|PONTO FRIO|PONTOFRIO|DELL|SAMSUNG|\bAPPLE\b(?!\.COM))', 'Eletrônicos', 48),
  ('transacao', '(LEROY|TUMELERO|CASSOL|QUERO.?QUERO|TOK ?STOK|\bETNA\b|FERRAGEM|FERRAGENS|MATERIAIS DE CONST|MAT CONST|HAVAN|CAMICADO|LOJAS AMERICANAS|AMERICANAS)', 'Casa e utilidades', 50),
  ('transacao', '(ESCOLA|COLEGIO|FACULDADE|UNIVERSIDADE|\bCURSO|UDEMY|ALURA|LIVRARIA|PAPELARIA|\bSENAC\b|\bSESI\b)', 'Educação', 50),
  ('transacao', '(CINEMA|CINEMARK|INGRESSO|SYMPLA|TEATRO|PARQUE|\bSTEAM\b|HOTEL|POUSADA|AIRBNB|BOOKING|DECOLAR|\bLATAM\b|GOL LINHAS|AZUL LINHAS|\bCLUBE\b|ACADEMIA|SMARTFIT|SMART FIT)', 'Lazer', 55),
  ('transacao', '(SALARIO|PROVENTOS|\bFOLHA\b|PAGTO SALARIO|\bFGTS\b|RENDIMENTO)', 'Receitas', 60)
) as r(alvo, padrao, categoria, prioridade)
join categorias c on c.nome = r.categoria
on conflict (alvo, tipo, padrao) do nothing;
